package tools.vitruv.framework.vsum.branch.storage;

// Source: Tural Mammadlee (feature/conflict-analyzer branch, Vitruv fork).
// Adapted with minor formatting changes only.

/**
 * Classifies the origin of a model change.
 *
 * <p>This classification is used during merge conflict resolution to apply the
 * Vitruvius rule: original changes (made by a human) are preferred over
 * consequential changes (generated by the engine).
 *
 * <p>Each {@link SemanticChangeEntry} stores one of these values so the merge
 * step can decide automatically when one side wins without human input.
 *
 * <p>The {@link #priority} value encodes this preference. Higher priority wins
 * when two conflicting entries have different origins.
 */
public enum ChangeOrigin {

  /**
   * A change physically made by a human developer in an editor.
   * This has the highest conflict-resolution priority.
   */
  ORIGINAL("Human-made change from an editor", 10),

  /**
   * A change triggered automatically by the Vitruvius consistency engine
   * to maintain cross-view consistency after an original change.
   * This has lower priority than ORIGINAL during conflict resolution.
   */
  CONSEQUENTIAL("Automatic change from the Vitruvius consistency engine", 5),

  /**
   * The origin could not be determined. Used for backward compatibility with
   * changelog entries recorded before origin tracking was introduced.
   */
  UNKNOWN("Origin could not be determined", 1);

  private final String description;
  private final int priority;

  ChangeOrigin(String description, int priority) {
    this.description = description;
    this.priority = priority;
  }

  /**
   * Returns a plain-English description of this origin category.
   */
  public String getDescription() {
    return description;
  }

  /**
   * Returns the conflict-resolution priority. Higher values win.
   * ORIGINAL (10) beats CONSEQUENTIAL (5) beats UNKNOWN (1).
   */
  public int getPriority() {
    return priority;
  }
}
