package tools.vitruv.framework.vsum.branch.storage;

// Source: Tural Mammadlee (feature/conflict-analyzer branch, Vitruv fork).
// Adapted with package and import changes only.

import java.util.ArrayList;
import java.util.List;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import tools.vitruv.framework.vsum.branch.data.SemanticConflict;
import tools.vitruv.framework.vsum.branch.data.UpdateConflict;
import tools.vitruv.framework.vsum.branch.data.UpdateConflict.Resolution;

/**
 * Analyzes a list of direct conflicts and attempts to resolve them automatically
 * using the origin information stored on each {@link SemanticChangeEntry}.
 *
 * <p>Resolution rule (from Tural Mammadlee's UpdateConflict design):
 * <ul>
 *   <li>One side {@link ChangeOrigin#ORIGINAL}, other side {@link ChangeOrigin#CONSEQUENTIAL}:
 *       auto-resolved. The ORIGINAL side wins because it is the developer's direct intent.
 *       The CONSEQUENTIAL side will be regenerated by the Vitruvius Reaction engine during
 *       replay and does not need to be replayed directly.</li>
 *   <li>Both sides the same origin, or either side {@link ChangeOrigin#UNKNOWN}:
 *       cannot be resolved automatically. Returned as {@link Resolution#NEEDS_HUMAN_REVIEW}.</li>
 * </ul>
 *
 * <p>Usage: call {@link #analyze(List)} with the conflicts from step 3, then use
 * {@link #filterUnresolved(List)} to extract only those that still need human review.
 */
public class UpdateConflictAnalyzer {

  private static final Logger LOGGER = LogManager.getLogger(UpdateConflictAnalyzer.class);

  /**
   * Analyzes each conflict and assigns a {@link Resolution} based on the origin of
   * the two changes involved.
   *
   * <p>A conflict is auto-resolvable when exactly one side is ORIGINAL and the other
   * is CONSEQUENTIAL. In all other cases the conflict is marked as
   * {@link Resolution#NEEDS_HUMAN_REVIEW}.
   *
   * @param conflicts the direct conflicts detected in step 3; must not be null.
   * @return a list of {@link UpdateConflict} objects with resolutions assigned.
   */
  public List<UpdateConflict> analyze(List<SemanticConflict> conflicts) {
    List<UpdateConflict> result = new ArrayList<>();
    int autoResolved = 0;

    for (SemanticConflict conflict : conflicts) {
      ChangeOrigin originA = conflict.getChangeOnBranchA().getOrigin();
      ChangeOrigin originB = conflict.getChangeOnBranchB().getOrigin();

      Resolution resolution = determineResolution(originA, originB);
      result.add(new UpdateConflict(conflict, resolution));

      if (resolution != Resolution.NEEDS_HUMAN_REVIEW) {
        autoResolved++;
        LOGGER.debug(
            "Auto-resolved conflict on element '{}' feature '{}': {} (A={}, B={})",
            conflict.getElementUuid(), conflict.getFeature(), resolution, originA, originB);
      }
    }

    LOGGER.info("Conflict analysis: {} total, {} auto-resolved, {} need human review",
        conflicts.size(), autoResolved, conflicts.size() - autoResolved);
    return result;
  }

  /**
   * Filters an analyzed list and returns only the conflicts that could not be
   * resolved automatically (i.e. those with {@link Resolution#NEEDS_HUMAN_REVIEW}).
   *
   * <p>Use this after {@link #analyze(List)} to get the list to return to the caller.
   *
   * @param analyzed the list returned by {@link #analyze(List)}; must not be null.
   * @return unresolved conflicts that require human intervention.
   */
  public List<SemanticConflict> filterUnresolved(List<UpdateConflict> analyzed) {
    List<SemanticConflict> unresolved = new ArrayList<>();
    for (UpdateConflict uc : analyzed) {
      if (!uc.isAutoResolved()) {
        unresolved.add(uc.getConflict());
      }
    }
    return unresolved;
  }

  /**
   * Determines the resolution for a single conflict given the origins of both sides.
   *
   * <p>Auto-resolution logic from Tural Mammadlee's UpdateConflict approach:
   * if one side is ORIGINAL and the other is CONSEQUENTIAL, the ORIGINAL side wins
   * automatically. Only conflicts where both sides have the same origin need human review.
   *
   * @param originA origin of the change on branch A.
   * @param originB origin of the change on branch B.
   * @return the {@link Resolution} for this conflict.
   */
  private Resolution determineResolution(ChangeOrigin originA, ChangeOrigin originB) {
    // UNKNOWN origin means we cannot trust auto-resolution; require human review.
    if (originA == ChangeOrigin.UNKNOWN || originB == ChangeOrigin.UNKNOWN) {
      return Resolution.NEEDS_HUMAN_REVIEW;
    }

    // ORIGINAL beats CONSEQUENTIAL: the developer's direct change wins.
    if (originA == ChangeOrigin.ORIGINAL && originB == ChangeOrigin.CONSEQUENTIAL) {
      return Resolution.AUTO_RESOLVED_BRANCH_A_WINS;
    }
    if (originB == ChangeOrigin.ORIGINAL && originA == ChangeOrigin.CONSEQUENTIAL) {
      return Resolution.AUTO_RESOLVED_BRANCH_B_WINS;
    }

    // Both ORIGINAL or both CONSEQUENTIAL: human must decide.
    return Resolution.NEEDS_HUMAN_REVIEW;
  }
}
