package tools.vitruv.framework.vsum.branch.merge;

// Source: anonymous author (paper companion code).
// Copied with package and import changes only.

import java.util.Objects;

/**
 * Data Transfer Object that represents a single atomic semantic change as used
 * by the merge engine.
 *
 * <p>This is the merge engine's internal representation of a change. It carries
 * the minimum set of fields that the {@link CommitDependencyGraph} needs to build
 * footprint-based dependency edges and that the replay engine needs to re-apply changes.
 *
 * <p>Instances are produced by {@link ChangeDtoDeserializer} from the stored
 * {@link tools.vitruv.framework.vsum.branch.storage.SemanticChangeEntry} records.
 *
 * <p>Note: {@code SemanticChangeLog.java} from the anonymous repo is not copied because
 * it overlaps with the existing changelog format. This class replaces the inner
 * {@code ChangeDto} that would have been defined there.
 */
public class ChangeDto {

  /** SHA of the commit that contains this change (7-char short form). */
  private final String commitSha;

  /** Stable UUID of the directly affected model element. */
  private final String affectedElementUuid;

  /** Name of the structural feature (attribute or reference) that was changed; null for lifecycle changes. */
  private final String featureName;

  /** Value before the change was applied; null if not applicable. */
  private final String oldValue;

  /** Value after the change was applied; null if not applicable. */
  private final String newValue;

  /** Change type string matching {@link tools.vitruv.framework.vsum.branch.storage.SemanticChangeType} name. */
  private final String changeType;

  /**
   * Whether this change was generated by the Vitruvius Reaction engine
   * (CONSEQUENTIAL) rather than directly by the developer (ORIGINAL).
   */
  private final boolean consequential;

  /**
   * Creates a new {@link ChangeDto}.
   *
   * @param commitSha            short SHA of the commit.
   * @param affectedElementUuid  UUID of the directly affected element.
   * @param featureName          structural feature name; null for lifecycle changes.
   * @param oldValue             previous value; null if not applicable.
   * @param newValue             new value; null if not applicable.
   * @param changeType           change type name.
   * @param consequential        true if this change was engine-generated.
   */
  public ChangeDto(String commitSha, String affectedElementUuid, String featureName,
      String oldValue, String newValue, String changeType, boolean consequential) {
    this.commitSha = Objects.requireNonNull(commitSha, "commitSha must not be null");
    this.affectedElementUuid = affectedElementUuid;
    this.featureName = featureName;
    this.oldValue = oldValue;
    this.newValue = newValue;
    this.changeType = Objects.requireNonNull(changeType, "changeType must not be null");
    this.consequential = consequential;
  }

  public String getCommitSha() {
    return commitSha;
  }

  public String getAffectedElementUuid() {
    return affectedElementUuid;
  }

  public String getFeatureName() {
    return featureName;
  }

  public String getOldValue() {
    return oldValue;
  }

  public String getNewValue() {
    return newValue;
  }

  public String getChangeType() {
    return changeType;
  }

  public boolean isConsequential() {
    return consequential;
  }

  @Override
  public String toString() {
    return "ChangeDto{"
        + "commitSha='" + commitSha + '\''
        + ", affectedElementUuid='" + affectedElementUuid + '\''
        + ", featureName='" + featureName + '\''
        + ", changeType='" + changeType + '\''
        + ", consequential=" + consequential
        + '}';
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangeDto that = (ChangeDto) o;
    return consequential == that.consequential
        && Objects.equals(commitSha, that.commitSha)
        && Objects.equals(affectedElementUuid, that.affectedElementUuid)
        && Objects.equals(featureName, that.featureName)
        && Objects.equals(oldValue, that.oldValue)
        && Objects.equals(newValue, that.newValue)
        && Objects.equals(changeType, that.changeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commitSha, affectedElementUuid, featureName, oldValue, newValue,
        changeType, consequential);
  }
}
