package tools.vitruv.framework.vsum.branch.merge;

// Source: anonymous author (paper companion code).
// Copied with package and import changes only.

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Captures the actual consequential footprint produced during replay (step 9).
 *
 * <p>During replay the Vitruvius Reaction engine fires and generates consequential changes.
 * This class collects those changes so that the iterative refinement step (step 9) can
 * compare the actual footprint against the estimated footprint used when building the
 * dependency graph. If new element-feature pairs are touched, the graph must be rebuilt.
 *
 * <p>One instance is used per replay session. Call {@link #record(String, ChangeDto)} each
 * time the engine generates a change, then call {@link #getActualFootprint(String)} to
 * retrieve the actual consequential footprint for a given commit.
 */
public class ChangeLogCapture {

  private static final Logger LOGGER = LogManager.getLogger(ChangeLogCapture.class);

  /** Actual consequential changes captured during replay, keyed by commit SHA. */
  private final Map<String, List<ChangeDto>> capturedChanges = new LinkedHashMap<>();

  /**
   * Records a consequential change generated by the Reaction engine during replay of the
   * given commit.
   *
   * @param commitSha the short SHA of the commit currently being replayed.
   * @param change    the consequential change captured from the engine output.
   */
  public void record(String commitSha, ChangeDto change) {
    capturedChanges.computeIfAbsent(commitSha, k -> new ArrayList<>()).add(change);
    LOGGER.debug("Captured consequential change for commit {}: {}", commitSha, change);
  }

  /**
   * Returns the list of consequential changes captured for the given commit during replay.
   *
   * @param commitSha the short SHA of the commit.
   * @return unmodifiable list of captured changes; empty if none were recorded.
   */
  public List<ChangeDto> getActualFootprint(String commitSha) {
    return Collections.unmodifiableList(
        capturedChanges.getOrDefault(commitSha, List.of()));
  }

  /**
   * Returns all captured changes across all commits.
   *
   * @return unmodifiable view of the full capture map.
   */
  public Map<String, List<ChangeDto>> getAllCaptured() {
    return Collections.unmodifiableMap(capturedChanges);
  }

  /**
   * Clears all captured changes (e.g. before a retry run).
   */
  public void reset() {
    capturedChanges.clear();
  }
}
